sonar.projectKey=kopipe
sonar.projectName=Kopipe
sonar.host.url=https://sonar.chundev.com

# Source
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx

sonar.exclusions=**/node_modules/**,**/.next/**,**/dist/**,**/coverage/**,**/*.config.*,**/scripts/**

# TypeScript
sonar.typescript.tsconfigPaths=tsconfig.json

# Encoding
sonar.sourceEncoding=UTF-8

# Coverage
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=src/server/api/trpc.ts,src/server/db.ts,src/trpc/server.ts,src/trpc/query-client.ts,src/app/api/trpc/**/route.ts,src/server/api/root.ts,src/env.js,src/components/ui/label.tsx,src/components/ui/sonner.tsx
